# Created by 254n_m
# ChunkBan Exploit Fix
# Permission to bypass all restrictions
# chunkban.bypass

#Message to send the player when a chunk ban is prevented
Prevent-Message: '&6Your message here'

#Maximum amount of tile entitys per chunk
TileEntity-Max: 512

#Maximum amount of skulls per chunk
Skull-Max: 100
 